{
	"version": 1530933457,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/block1-sheet0.png",
		"images/block2-sheet0.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/coin-sheet2.png",
		"images/enemy-sheet0.png",
		"images/bg_game.png",
		"images/start-sheet0.png",
		"images/wall-sheet0.png",
		"images/bg_title.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/again-sheet0.png",
		"images/bg_score.png",
		"images/tiledbackground3.png",
		"images/music-sheet0.png",
		"images/music-sheet1.png",
		"images/rank2-sheet0.png",
		"media/bgm.ogg"
	]
}